if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

install.packages("devtools")
install.packages("readr")
install.packages("pheatmap")
install.packages("tibble")
install.packages("ggpubr")
install.packages("openxlsx", dependencies = TRUE)
install.packages('reticulate')
install.packages("harmony")
install.packages('DT')

BiocManager::install(c("LoomExperiment", "SingleCellExperiment"))
devtools::install_github("cellgeni/sceasy")
BiocManager::install("progeny")
devtools::install_github("saezlab/progeny")
devtools::install_github('immunogenomics/presto')
BiocManager::install("MAST")